// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-organization-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var OVERVIEW = `Cybersecurity Leadership (CSL) \u2014 powered by Monarch217 \u2014 is a practitioner-led leadership platform for executives, boards, and community leaders navigating cyber risk, AI adoption, and governance.

Positioning: trust over transaction, leader-controlled outcomes, and an ongoing platform (not a one-off vendor engagement). Legal status: 501(c)(3) pending. No vendor agenda; member-first and neutral.

Core focus areas:
- Cybersecurity leadership and executive readiness
- AI governance and responsible AI adoption
- Executive cohorts and advisory services
- Ziggy \u2014 an Executive Intelligence Operating System (private preview)

Website: https://cybersecurity-leadership.org
Founder: George Cater IV \u2014 practitioner-led positioning.`;
var get_organization_overview_default = defineTool({
  name: "get_organization_overview",
  title: "Organization overview",
  description: "Returns a high-level overview of Cybersecurity Leadership (CSL) / Monarch217: mission, positioning, focus areas, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: OVERVIEW }],
    structuredContent: {
      name: "Cybersecurity Leadership (CSL)",
      brand: "Monarch217",
      website: "https://cybersecurity-leadership.org",
      founder: "George Cater IV",
      legalStatus: "501(c)(3) pending",
      focusAreas: [
        "Cybersecurity leadership",
        "AI governance",
        "Executive cohorts",
        "Advisory services",
        "Ziggy \u2014 Executive Intelligence Operating System"
      ]
    }
  })
});

// src/lib/mcp/tools/list-offerings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var OFFERINGS = [
  {
    name: "Membership",
    summary: "Executive membership in the Cybersecurity Leadership platform. Trust-first community for leaders navigating cyber risk and AI governance.",
    path: "/membership",
    cta: "Join"
  },
  {
    name: "Executive Cohorts",
    summary: "Practitioner-led cohorts for executives building leadership capability across cybersecurity and AI adoption.",
    path: "/cohort",
    cta: "Book a call"
  },
  {
    name: "AI Governance",
    summary: "Governance program for organizations adopting AI responsibly, with practical operating structure and human oversight.",
    path: "/services/ai-governance",
    cta: "Request"
  },
  {
    name: "Advisory Services",
    summary: "Direct advisory engagements for executives and boards on cyber risk, AI governance, and leadership strategy.",
    path: "/services/advisory",
    cta: "Book a call"
  },
  {
    name: "Strategic Partnerships",
    summary: "Partnership opportunities for organizations aligned with the platform's mission.",
    path: "/strategic-partners",
    cta: "Apply"
  },
  {
    name: "Ziggy \u2014 Executive Intelligence Operating System",
    summary: "A relationship-first Executive Intelligence Operating System with a warm companion interface, built on trust, privacy, human approval, and closed-loop execution. Currently in private preview.",
    path: "/ziggy",
    cta: "Request private preview"
  }
];
var BASE = "https://cybersecurity-leadership.org";
var list_offerings_default = defineTool2({
  name: "list_offerings",
  title: "List offerings",
  description: "Lists the programs and services offered by Cybersecurity Leadership (membership, cohorts, AI governance, advisory, partnerships, and Ziggy) with a short summary and page link for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = OFFERINGS.map((o) => ({ ...o, url: `${BASE}${o.path}` }));
    const text = items.map((o) => `\u2022 ${o.name}
  ${o.summary}
  ${o.url}`).join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { offerings: items }
    };
  }
});

// src/lib/mcp/tools/get-contact-and-booking.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var BASE2 = "https://cybersecurity-leadership.org";
var CONTACT = {
  bookACall: `${BASE2}/book`,
  join: `${BASE2}/membership`,
  events: `${BASE2}/events`,
  register: `${BASE2}/register`,
  strategicPartners: `${BASE2}/strategic-partners`,
  requestZiggyPreview: `${BASE2}/ziggy`
};
var get_contact_and_booking_default = defineTool3({
  name: "get_contact_and_booking",
  title: "Contact & booking links",
  description: "Returns the canonical links for engaging with Cybersecurity Leadership: booking a strategy call, joining as a member, viewing events, registering, partnership inquiries, and requesting a Ziggy private preview.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = [
      `Book a strategy call: ${CONTACT.bookACall}`,
      `Join / Membership: ${CONTACT.join}`,
      `Events: ${CONTACT.events}`,
      `Register for an event: ${CONTACT.register}`,
      `Strategic partnerships: ${CONTACT.strategicPartners}`,
      `Request a Ziggy private preview: ${CONTACT.requestZiggyPreview}`
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: CONTACT
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cybersecurity-leadership-mcp",
  title: "Cybersecurity Leadership MCP",
  version: "0.1.0",
  instructions: "Tools for Cybersecurity Leadership (CSL) / Monarch217, a practitioner-led leadership platform for cyber risk, AI governance, and executive readiness. Use `get_organization_overview` for context, `list_offerings` for programs and services, and `get_contact_and_booking` for engagement links.",
  tools: [get_organization_overview_default, list_offerings_default, get_contact_and_booking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
